# test/succfail.p, 1: program PredSuccFail() is
# test/succfail.p, 2: type e is (zero, one, two, three, four);
    0: calli 0, 2
    1: halt
# test/succfail.p, 3: begin
# test/succfail.p, 4: 	putln(succ(four))
    2: push 4
    3: succ 4
    4: push 1
    5: push 0
    6: push 0
# test/succfail.p, 5: endprog
    7: putln
# test/succfail.p, 6: 
    8: ret 0

runtime error @pc 3, sp: 8: out-of-range
